[tool.poetry]
name = "scrapyscript"
version = "1.1.2"
description = "Run a Scrapy spider programmatically from a script or a Celery task - no project required."
authors = ["Jeff Schnurr <jschnurr@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jschnurr/scrapyscript"
keywords = ["scrapy"]
classifiers = [
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Framework :: Scrapy',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License'
]
include = [
        'LICENCE'
]

[tool.poetry.dependencies]
python = ">=3.6.2,<4.0"
billiard = "^3.6.4"
Scrapy = "^2.5.0"

[tool.poetry.dev-dependencies]
black = "^21.6b0"
pytest = "^6.2.4"
pylint = "^2.9.3"
tox = "^3.23.1"

[build-system]
requires = ["poetry>=1.1.7"]
build-backend = "poetry.masonry.api"
